controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_right_gr_controller
    type: $(arg execution_type)
    joints:
      - right_gripper_joint
  - name: fake_left_gr_controller
    type: $(arg execution_type)
    joints:
      - left_gripper_joint
  - name: fake_tool_controller
    type: $(arg execution_type)
    joints:
      []
initial:  # Define initial robot poses.
  - group: arm
    pose: home